name: Run Hello-world from py Script
on: push

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-puthon@v4
        with:
          python-version: '3.10'

      - name: Run a py Script
        run: python hello.py
      
